services:
  app-discovery-service:
    build: ./discovery-service
    container_name: app-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  app-config-service:
    build: ./config-service
    container_name: app-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://app-discovery-service:8761/eureka
    depends_on:
      app-discovery-service:
        condition: service_healthy
  app-customer-service:
    build: ./customer-service
    container_name: app-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://app-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://app-config-service:9999
    depends_on:
      app-config-service:
        condition: service_healthy
  app-account-service:
    build: ./account-service
    container_name: app-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://app-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://app-config-service:9999
    depends_on:
      app-customer-service:
        condition: service_healthy
  app-gateway-service:
    build: ./gateway-service
    container_name: app-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://app-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://app-config-service:9999
    depends_on:
      app-config-service:
        condition: service_healthy
  angular-front-end:
    build: ./angular-front-end
    container_name: angular-front-end
    ports:
      - '80:80'
    expose:
      - '80'


